import globals from 'globals';
import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';
import stylisticJs from '@stylistic/eslint-plugin-js';

const indentSpaces = 4;
const maxLen = 80;

export default [
    js.configs.recommended,
    jsdoc.configs['flat/recommended'],
    { plugins: { '@stylistic/js': stylisticJs } },
    {
        rules: {
            '@stylistic/js/array-bracket-spacing': 'error',
            'array-callback-return': ['error', { checkForEach: true }],
            'arrow-body-style': 'error',
            '@stylistic/js/arrow-parens': ['error', 'as-needed'],
            '@stylistic/js/arrow-spacing': 'warn',
            '@stylistic/js/block-spacing': 'warn',
            '@stylistic/js/brace-style':
                ['error', '1tbs', { 'allowSingleLine': true }],
            '@stylistic/js/comma-dangle': ['error', 'always-multiline'],
            '@stylistic/js/comma-spacing': 'error',
            '@stylistic/js/comma-style': 'error',
            curly: ['error', 'multi-line', 'consistent'],
            '@stylistic/js/computed-property-spacing': 'warn',
            '@stylistic/js/dot-location': ['error', 'property'],
            'dot-notation': 'error',
            '@stylistic/js/eol-last': 'error',
            eqeqeq: 'error',
            '@stylistic/js/function-call-spacing': 'error',
            '@stylistic/js/implicit-arrow-linebreak': 'error',
            '@stylistic/js/indent':
                ['error', indentSpaces, { 'SwitchCase': 1 }],
            '@stylistic/js/key-spacing': 'error',
            '@stylistic/js/keyword-spacing': 'error',
            '@stylistic/js/linebreak-style': 'error',
            'logical-assignment-operators':
                ['error', 'always', { enforceForIfStatements: true }],
            'max-nested-callbacks': ['error', { 'max': 4 }],
            '@stylistic/js/max-len': ['warn', maxLen],
            '@stylistic/js/max-statements-per-line': 'error',
            '@stylistic/js/multiline-comment-style': ['warn', 'starred-block'],
            '@stylistic/js/multiline-ternary': ['error', 'always-multiline'],
            '@stylistic/js/new-parens': 'error',
            'no-console': 'off',
            '@stylistic/js/no-confusing-arrow': 'error',
            'no-duplicate-imports': 'error',
            'no-empty-function': 'error',
            '@stylistic/js/no-extra-parens': 'error',
            '@stylistic/js/no-extra-semi': 'error',
            '@stylistic/js/no-floating-decimal': 'error',
            'no-implicit-coercion': 'error',
            'no-inline-comments': 'warn',
            'no-lonely-if': 'error',
            'no-magic-numbers': ['warn', { ignoreArrayIndexes: true }],
            '@stylistic/js/no-multi-spaces': 'error',
            '@stylistic/js/no-multiple-empty-lines': ['error',
                { max: 2, maxEOF: 1, maxBOF: 0 }],
            'no-nested-ternary': 'error',
            'no-promise-executor-return': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-shadow': ['error', { 'allow': ['err', 'resolve', 'reject'] }],
            'no-template-curly-in-string': 'warn',
            '@stylistic/js/no-trailing-spaces': 'error',
            'no-unmodified-loop-condition': 'warn',
            'no-unneeded-ternary': 'error',
            'no-unreachable-loop': 'warn',
            'no-use-before-define': ['error', { functions: false }],
            'no-useless-assignment': 'error',
            'no-var': 'error',
            '@stylistic/js/no-whitespace-before-property': 'error',
            '@stylistic/js/object-curly-newline':
                ['error', { 'consistent': true }],
            '@stylistic/js/object-curly-spacing': ['error', 'always'],
            'object-shorthand': 'warn',
            '@stylistic/js/one-var-declaration-per-line': 'warn',
            '@stylistic/js/operator-linebreak': 'error',
            '@stylistic/js/padded-blocks': ['error', 'never'],
            'prefer-const': 'error',
            '@stylistic/js/quotes': ['error', 'single'],
            'require-atomic-updates': 'error',
            '@stylistic/js/rest-spread-spacing': 'error',
            '@stylistic/js/semi': ['error', 'always'],
            '@stylistic/js/semi-spacing': 'error',
            '@stylistic/js/semi-style': 'error',
            'sort-imports': 'error',
            '@stylistic/js/space-before-blocks': 'error',
            '@stylistic/js/space-before-function-paren': ['error',
                { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
            '@stylistic/js/space-in-parens': 'error',
            '@stylistic/js/space-infix-ops': 'error',
            '@stylistic/js/space-unary-ops': 'error',
            '@stylistic/js/spaced-comment': 'error',
            '@stylistic/js/switch-colon-spacing': 'error',
            '@stylistic/js/template-curly-spacing': 'error',
            '@stylistic/js/template-tag-spacing': 'error',
            yoda: 'error',
        },
    },
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...globals.es5,
            },
        },
    },
];
